
import Footer from "@/Components/Footer";
import "./globals.css";
import NavigationBar from "@/Components/navigationBar";
import Footers from "@/Components/Footers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className=""
      >

      <header className=" container mx-auto  border-b border-gray-200 "> 
          <NavigationBar />
      </header>

       <main className="my-5">

         {children}

       </main>

      
      <footer>
          {/* <Footer/> */}

          <Footers/>
      </footer>

      
      </body>
    </html>
  );
}
